# =========================
# Stage 1 - Build
# =========================
FROM python:3.13-slim AS build

WORKDIR /app

COPY requirements.txt .

RUN pip install \
    --no-cache-dir \
    --target=/install \
    -r requirements.txt

COPY src/ ./src/


# =========================
# Stage 2 - Runtime
# =========================
FROM python:3.13-slim

WORKDIR /app

COPY --from=build /install /usr/local/lib/python3.13/site-packages
COPY --from=build /app/src ./src

ENV ENVIRONMENT=docker
ENV APP_VERSION=1.0.0

EXPOSE 5000

ENTRYPOINT ["gunicorn"]

CMD ["--bind", "0.0.0.0:5000", "src.app:app"]
